# Generated by Django 3.1 on 2021-06-02 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], verbose_name='Hour')),
                ('minute', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], null=True, verbose_name='Minute')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], help_text='no effect atm', null=True, verbose_name='Day Of Month')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='no effect atm', null=True, verbose_name='Day Of Week')),
                ('command', models.CharField(max_length=1024, verbose_name='Command')),
                ('active', models.BooleanField(default=True, help_text='Disabled if unchecked', verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='QueuedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Modified')),
                ('command', models.CharField(max_length=1024, verbose_name='Command')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (10, 'Running'), (20, 'Done'), (30, 'Failed'), (40, 'Killed')], default=0, verbose_name='Status')),
                ('stdout', models.TextField(blank=True, max_length=4096, verbose_name='Standard Output')),
                ('stderr', models.TextField(blank=True, max_length=4096, verbose_name='Standard Error')),
                ('crontask', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_tasks', to='async_que.crontask', verbose_name='CronTask')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created')),
                ('event_type', models.PositiveIntegerField(choices=[(50, 'Error'), (100, 'Event Log'), (300, 'Application Programming Interface'), (350, 'Authentication'), (400, 'Debugging Log'), (500, 'Teaching Log')], default=100, verbose_name='Event Type')),
                ('summary', models.CharField(help_text='Text Shown in Staff Event Log', max_length=132, verbose_name='Summary')),
                ('show', models.BooleanField(default=False, help_text='Show in Staff Event Log', verbose_name='Show')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('extra_detail', models.TextField(blank=True, verbose_name='Extra Detail')),
                ('logged_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
