version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: async_web
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
volumes:
  db-data:
    driver: local
